### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by TimoBehrendt** [johannesfritsch/passbolt-api#2]
Ahoy, I've been working with Passbolt for quite some time and came across your repo. I would love to work with it but do not feel comfortable to do so without a license attached to the project.

I would suggest going for MIT or a if you insist on keeping subsequent project open source as well: GNU General Public License v3.0.

**Comment by nigimaxx** [comment]
Hi @TimoBehrendt, I've added an MIT license.

**Comment by TimoBehrendt** [comment]
Thank you!
